### ISSUE TITLE
 Compatibility Issue with python-telegram-bot v21+

### ISSUE THREAD

**Issue by robelasefa** [LucaSforza/MongoPersistence#17]
### Description:

I'm encountering a version conflict when installing `mongopersistence` alongside the latest version of python-telegram-bot (v21.1.1).

`mongopersistence` appears to have a dependency on an older version of `python-telegram-bot` (v20.8). This creates a conflict when I try to install both packages using `pip install -r requirements.txt`.

### Desired Behavior:

- I'd like to be able to use the latest features available in `python-telegram-bot` v21.1.1 while still utilizing `mongopersistence` for data persistence.

### Possible Solutions:

**1. Investigated Compatibility: (If applicable)**

- I've checked the documentation for both libraries, but haven't found definitive information about compatibility with `python-telegram-bot` v21 or later.

**2. Isolated Environment: (If applicable)**

- While I can use a virtual environment to isolate dependencies for my project, I'd prefer a broader solution to avoid managing multiple environments.

### Request:

- Could you please investigate potential compatibility between `mongopersistence` and newer versions of `python-telegram-bot`?
- If compatibility is not currently supported, are there plans to address this in future releases?

### Additional Information:

- Python version: v3.12.3
- `mongopersistence` version: v0.3.0
- `python-telegram-bot` version: v21.1.1

**Comment by rabilrbl** [comment]
@robelasefa I have fixed it in my forked version.
You can install/mention it via `git+https://github.com/rabilrbl/MongoPersistence.git@main`

**Comment by LucaSforza** [comment]
Resolved thanks to #18, please update using pip to the version 0.3.1 of mongopersistence
